include(CMakeDependentOption)

cmake_dependent_option(RKAIQ_BUILD_DOCS "Build all of rkaiq's documents." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_TESTS "Build all of rkaiq's own tests." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_EXAMPLES "Build all of rkaiq's own examples." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_ASAN "Build libraries/executable with address santilizer" OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_SIMULATOR "Build simulator for algos run on PC" OFF "WIN32" OFF)
set(RKAIQ_ENABLE_PARSER_V1   FALSE CACHE INTERNAL "Build rkaiq's old xml parser")
set(RKAIQ_ENABLE_CAMGROUP    FALSE CACHE INTERNAL "Build rkaiq's camera group algorithms")

message(STATUS "Building ISP rkaiq for soc ${RKAIQ_TARGET_SOC}")
if (RKAIQ_TARGET_SOC STREQUAL "rv1106")
    set(RKAIQ_ISP_VERSION        "32"  CACHE INTERNAL "ISP hardware version 32"               FORCE)
    set(RKAIQ_ENABLE_PARSER_V1   FALSE CACHE INTERNAL "Build rkaiq's old xml parser"          FORCE)
    set(RKAIQ_ENABLE_CAMGROUP    FALSE CACHE INTERNAL "Build rkaiq's camera group algorithms" FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk3588")
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "ISP hardware version 30"               FORCE)
    set(RKAIQ_ENABLE_PARSER_V1   FALSE CACHE INTERNAL "Build rkaiq's old xml parser"          FORCE)
    set(RKAIQ_ENABLE_CAMGROUP    TRUE  CACHE INTERNAL "Build rkaiq's camera group algorithms" FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk356x")
    set(RKAIQ_ISP_VERSION        "21"  CACHE INTERNAL "ISP hardware version 21"               FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rv1109")
    set(RKAIQ_ISP_VERSION        "20"  CACHE INTERNAL "ISP hardware version 20"               FORCE)
else()
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "No ISP hardware version specificed"    FORCE)
    message(WARNING "RKAIQ_TARGET_SOC SHOULD be set")
endif()

if (ISP_HW_VERSION STRLESS "-DISP_HW_V20")
    message(FATAL_ERROR "ISP_HW_VERSION MUST be set")
endif()

if (RKAIQ_ISP_VERSION STREQUAL "32")
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V10  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   TURE  CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   TURE  CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 TURE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  TURE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   TURE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TURE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TURE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   TRUE  CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V2   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 2"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V1   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V2   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 2"       FORCE)
	set(RKAIQ_HAVE_DRC_V1   FALSE CACHE INTERNAL "Build rkaiq's DRC version 1"       FORCE)
	set(RKAIQ_HAVE_DRC_V2   TRUE CACHE INTERNAL "Build rkaiq's DRC version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V1   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 1"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V2   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V3   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 3"       FORCE)
	set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
	set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "30")
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V10  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   TURE  CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   TURE  CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 TURE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  TURE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   TURE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TURE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TURE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   TRUE  CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V2   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 2"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V1   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V2   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 2"       FORCE)
	set(RKAIQ_HAVE_DRC_V1   FALSE CACHE INTERNAL "Build rkaiq's DRC version 1"       FORCE)
	set(RKAIQ_HAVE_DRC_V2   TRUE CACHE INTERNAL "Build rkaiq's DRC version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V1   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 1"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V2   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V3   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 3"       FORCE)
	set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
	set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "21")
    set(RKAIQ_HAVE_YNR_V2   TRUE  CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   TRUE  CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  TRUE  CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   TRUE  CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V2   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 2"       FORCE)
	set(RKAIQ_HAVE_MERGE_V1   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V2   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 2"       FORCE)
	set(RKAIQ_HAVE_DRC_V1   TRUE CACHE INTERNAL "Build rkaiq's DRC version 1"       FORCE)
	set(RKAIQ_HAVE_DRC_V2   FALSE CACHE INTERNAL "Build rkaiq's DRC version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V1   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 1"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V2   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V3   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 3"       FORCE)
	set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
	set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "20")
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_AWB_V20  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   TRUE  CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   TRUE  CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_SHARP_V1 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   TRUE  CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   TRUE  CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V2   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 2"       FORCE)
	set(RKAIQ_HAVE_MERGE_V1   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V2   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 2"       FORCE)
	set(RKAIQ_HAVE_DRC_V1   FALSE CACHE INTERNAL "Build rkaiq's DRC version 1"       FORCE)
	set(RKAIQ_HAVE_DRC_V2   FALSE CACHE INTERNAL "Build rkaiq's DRC version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V1   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 1"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V2   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V3   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 3"       FORCE)
	set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_TMO_V1   TRUE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
	set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
else()
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Don't build rkaiq's YNR version 2" FORCE)
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 FALSE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"     FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_GAMMA_V2   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 2"       FORCE)
	set(RKAIQ_HAVE_MERGE_V1   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 1"       FORCE)
	set(RKAIQ_HAVE_MERGE_V2   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 2"       FORCE)
	set(RKAIQ_HAVE_DRC_V1   FALSE CACHE INTERNAL "Build rkaiq's DRC version 1"       FORCE)
	set(RKAIQ_HAVE_DRC_V2   FALSE CACHE INTERNAL "Build rkaiq's DRC version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V1   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 1"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V2   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 2"       FORCE)
	set(RKAIQ_HAVE_DEHAZE_V3   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 3"       FORCE)
	set(RKAIQ_HAVE_DEGAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
	set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
	set(RKAIQ_HAVE_WDR_V1   FALSE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
endif()

